server:
  port: 3010

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: auth-demo

jwt:
  secret:
    key: 2lk3h5j3kh534k5uiss8hs78a8h3ruwlrjhwkhdwkhk2hrk4jhkh2u3h7f8hsdflfuhj

management:
  endpoints:
    web:
      exposure:
        include: '*'


